DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS PUBLISHERS;
DROP TABLE IF EXISTS GENRES;

CREATE TABLE AUTHORS
(
    ID        BIGSERIAL PRIMARY KEY,
    FULL_NAME VARCHAR(255) NOT NULL,
    BIRTHDAY  NUMERIC(4, 0)
);

CREATE TABLE PUBLISHERS
(
    ID   BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE GENRES
(
    ID   BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE BOOKS
(
    ID           BIGSERIAL PRIMARY KEY,
    TITLE        VARCHAR(255) NOT NULL,
    AUTHOR_ID    BIGINT       NOT NULL,
    GENRE_ID     BIGINT       NOT NULL,
    PUBLISHER_ID BIGINT       NOT NULL,
    PUBLISH_YEAR INT          NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID),
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID),
    FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHERS (ID)
);
