DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS PUBLISHERS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS
(
    ID       BIGINT AUTO_INCREMENT,
    USERNAME VARCHAR(50)  NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    ENABLED  TINYINT(1)   NOT NULL DEFAULT 1,
    ROLE     VARCHAR(200) NOT NULL DEFAULT 'ROLE_READER',
    PRIMARY KEY (ID),
    UNIQUE KEY USERS_UNIQ_USERNAME (USERNAME)
);

CREATE TABLE AUTHORS
(
    ID        BIGINT AUTO_INCREMENT,
    FULL_NAME VARCHAR(255) NOT NULL,
    BIRTHDAY  NUMERIC(4, 0),
    PRIMARY KEY (ID)
);

CREATE TABLE PUBLISHERS
(
    ID   BIGINT AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE GENRES
(
    ID   BIGINT AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE BOOKS
(
    ID           BIGINT AUTO_INCREMENT,
    TITLE        VARCHAR(255) NOT NULL,
    AUTHOR_ID    BIGINT       NOT NULL,
    GENRE_ID     BIGINT       NOT NULL,
    PUBLISHER_ID BIGINT       NOT NULL,
    PUBLISH_YEAR INT          NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID),
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID),
    FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHERS (ID)
);
